-- MySQL Script generated by MySQL Workbench
-- Sun Sep 10 17:30:49 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `IdROLES` INT(11) NOT NULL AUTO_INCREMENT,
  `Nombres_Roles` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`IdROLES`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `idUSUARIOS` INT(11) NOT NULL AUTO_INCREMENT,
  `usuarios_nombres` VARCHAR(45) NOT NULL,
  `usuario_apellido` VARCHAR(45) NOT NULL,
  `usuario_username` VARCHAR(45) NOT NULL,
  `usuario_contraseña` VARCHAR(45) NOT NULL,
  `usuario_correo` VARCHAR(45) NOT NULL,
  `ROLES_IdROLES` INT(11) NOT NULL,
  PRIMARY KEY (`idUSUARIOS`),
  INDEX `fk_USUARIOS_ROLES_idx` (`ROLES_IdROLES` ASC) ,
  CONSTRAINT `fk_USUARIOS_ROLES`
    FOREIGN KEY (`ROLES_IdROLES`)
    REFERENCES `mydb`.`roles` (`IdROLES`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 23
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idCLIENTES` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIOS_idUSUARIOS` INT(11) NOT NULL,
  PRIMARY KEY (`idCLIENTES`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`USUARIOS_idUSUARIOS` ASC) ,
  CONSTRAINT `fk_CLIENTES_USUARIOS1`
    FOREIGN KEY (`USUARIOS_idUSUARIOS`)
    REFERENCES `mydb`.`usuarios` (`idUSUARIOS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`citas` (
  `IdCITAS` INT(11) NOT NULL AUTO_INCREMENT,
  `Citas_fechas` DATETIME NOT NULL,
  `CLIENTES_idCLIENTES` INT(11) NOT NULL,
  PRIMARY KEY (`IdCITAS`),
  INDEX `fk_CITAS_CLIENTES1_idx` (`CLIENTES_idCLIENTES` ASC) ,
  CONSTRAINT `fk_CITAS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_idCLIENTES`)
    REFERENCES `mydb`.`clientes` (`idCLIENTES`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estilistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estilistas` (
  `idESTILISTAS` INT(11) NOT NULL AUTO_INCREMENT,
  `USUARIOS_idUSUARIOS` INT(11) NOT NULL,
  PRIMARY KEY (`idESTILISTAS`),
  INDEX `fk_CLIENTES_USUARIOS1_idx` (`USUARIOS_idUSUARIOS` ASC) ,
  CONSTRAINT `fk_CLIENTES_USUARIOS10`
    FOREIGN KEY (`USUARIOS_idUSUARIOS`)
    REFERENCES `mydb`.`usuarios` (`idUSUARIOS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`formas_de_pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formas_de_pagos` (
  `idFORMAS_DE_PAGOS` INT(11) NOT NULL AUTO_INCREMENT,
  `pago_nombre` VARCHAR(45) NOT NULL,
  `estado_del_pago` TINYINT(4) NOT NULL,
  PRIMARY KEY (`idFORMAS_DE_PAGOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idPRODUCTOS` INT(11) NOT NULL AUTO_INCREMENT,
  `producto_nombre` VARCHAR(45) NOT NULL,
  `producto_precio` VARCHAR(45) NOT NULL,
  `producto_cantidad` INT(11) NOT NULL,
  `Imagen_productos` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`idPRODUCTOS`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`servicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicios` (
  `idSERVICIOS` INT(11) NOT NULL AUTO_INCREMENT,
  `servicio_nombre` VARCHAR(45) NOT NULL,
  `servicio_valor` VARCHAR(45) NOT NULL,
  `servicio_cantidad` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`idSERVICIOS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`facturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`facturas` (
  `idFACTURAS` INT(11) NOT NULL AUTO_INCREMENT,
  `factura_fecha` DATETIME NOT NULL,
  `factura_total_productos` DECIMAL(7,2) NOT NULL,
  `factura_total_servicios` DECIMAL(7,2) NOT NULL,
  `factura_total` DECIMAL(7,2) NOT NULL,
  `CLIENTES_idCLIENTES` INT(11) NOT NULL,
  `FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS` INT(11) NOT NULL,
  `SERVICIOS_idSERVICIOS` INT(11) NOT NULL,
  `PRODUCTOS_idPRODUCTOS` INT(11) NOT NULL,
  PRIMARY KEY (`idFACTURAS`),
  INDEX `fk_FACTURAS_CLIENTES1_idx` (`CLIENTES_idCLIENTES` ASC) ,
  INDEX `fk_FACTURAS_FORMAS_DE_PAGOS1_idx` (`FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS` ASC) ,
  INDEX `fk_FACTURAS_SERVICIOS1_idx` (`SERVICIOS_idSERVICIOS` ASC) ,
  INDEX `fk_FACTURAS_PRODUCTOS1_idx` (`PRODUCTOS_idPRODUCTOS` ASC) ,
  CONSTRAINT `fk_FACTURAS_CLIENTES1`
    FOREIGN KEY (`CLIENTES_idCLIENTES`)
    REFERENCES `mydb`.`clientes` (`idCLIENTES`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FACTURAS_FORMAS_DE_PAGOS1`
    FOREIGN KEY (`FORMAS_DE_PAGOS_idFORMAS_DE_PAGOS`)
    REFERENCES `mydb`.`formas_de_pagos` (`idFORMAS_DE_PAGOS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FACTURAS_PRODUCTOS1`
    FOREIGN KEY (`PRODUCTOS_idPRODUCTOS`)
    REFERENCES `mydb`.`productos` (`idPRODUCTOS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_FACTURAS_SERVICIOS1`
    FOREIGN KEY (`SERVICIOS_idSERVICIOS`)
    REFERENCES `mydb`.`servicios` (`idSERVICIOS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comisiones` (
  `IdCOMISIONES` INT(11) NOT NULL AUTO_INCREMENT,
  `comision_pagar` VARCHAR(45) NOT NULL,
  `comision_estado_pago` TINYINT(4) NOT NULL,
  `ESTILISTAS_idESTILISTAS` INT(11) NOT NULL,
  `FACTURAS_idFACTURAS` INT(11) NOT NULL,
  PRIMARY KEY (`IdCOMISIONES`),
  INDEX `fk_COMISIONES_ESTILISTAS1_idx` (`ESTILISTAS_idESTILISTAS` ASC) ,
  INDEX `fk_COMISIONES_FACTURAS1_idx` (`FACTURAS_idFACTURAS` ASC) ,
  CONSTRAINT `fk_COMISIONES_ESTILISTAS1`
    FOREIGN KEY (`ESTILISTAS_idESTILISTAS`)
    REFERENCES `mydb`.`estilistas` (`idESTILISTAS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_COMISIONES_FACTURAS1`
    FOREIGN KEY (`FACTURAS_idFACTURAS`)
    REFERENCES `mydb`.`facturas` (`idFACTURAS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`estilistas_has_citas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estilistas_has_citas` (
  `ESTILISTAS_idESTILISTAS` INT(11) NOT NULL,
  `CITAS_IdCITAS` INT(11) NOT NULL,
  `Esteticistas_estado` TINYINT(4) NOT NULL,
  INDEX `fk_ESTILISTAS_has_CITAS_ESTILISTAS1_idx` (`ESTILISTAS_idESTILISTAS` ASC) ,
  INDEX `fk_ESTILISTAS_has_CITAS_CITAS1_idx` (`CITAS_IdCITAS` ASC) ,
  CONSTRAINT `fk_ESTILISTAS_has_CITAS_CITAS1`
    FOREIGN KEY (`CITAS_IdCITAS`)
    REFERENCES `mydb`.`citas` (`IdCITAS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_ESTILISTAS_has_CITAS_ESTILISTAS1`
    FOREIGN KEY (`ESTILISTAS_idESTILISTAS`)
    REFERENCES `mydb`.`estilistas` (`idESTILISTAS`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
